# Generated by Django 2.1.3 on 2018-11-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('NU_INSCRICAO', models.CharField(max_length=100)),
                ('NU_ANO', models.CharField(max_length=100)),
                ('CO_MUNICIPIO_RESIDENCIA', models.CharField(max_length=100)),
                ('NO_MUNICIPIO_RESIDENCIA', models.CharField(max_length=100)),
                ('SG_UF_RESIDENCIA', models.CharField(max_length=100)),
                ('NU_IDADE', models.IntegerField()),
                ('TP_SEXO', models.CharField(max_length=100)),
                ('TP_ESTADO_CIVIL', models.CharField(max_length=100)),
                ('TP_COR_RACA', models.CharField(max_length=100)),
                ('TP_NACIONALIDADE', models.CharField(max_length=100)),
                ('CO_MUNICIPIO_NASCIMENTO', models.CharField(max_length=100)),
                ('NO_MUNICIPIO_NASCIMENTO', models.CharField(max_length=100)),
                ('SG_UF_NASCIMENTO', models.CharField(max_length=100)),
                ('TP_ST_CONCLUSAO', models.CharField(max_length=100)),
                ('TP_ANO_CONCLUIU', models.CharField(max_length=100)),
                ('TP_ESCOLA', models.CharField(max_length=100)),
                ('TP_ENSINO', models.CharField(max_length=100)),
                ('IN_TREINEIRO', models.CharField(max_length=100)),
                ('CO_ESCOLA', models.CharField(max_length=100)),
                ('CO_MUNICIPIO_ESC', models.CharField(max_length=100)),
                ('NO_MUNICIPIO_ESC', models.CharField(max_length=100)),
                ('SG_UF_ESC', models.CharField(max_length=100)),
                ('TP_DEPENDENCIA_ADM_ESC', models.CharField(max_length=100)),
                ('TP_LOCALIZACAO_ESC', models.CharField(max_length=100)),
                ('IN_CEGUEIRA', models.CharField(max_length=100)),
                ('IN_SURDEZ', models.CharField(max_length=100)),
                ('IN_DEFICIENCIA_AUDITIVA', models.CharField(max_length=100)),
                ('IN_SURDO_CEGUEIRA', models.CharField(max_length=100)),
                ('IN_DEFICIENCIA_MENTAL', models.CharField(max_length=100)),
                ('IN_DEFICIT_ATENCAO', models.CharField(max_length=100)),
                ('IN_DISLEXIA', models.CharField(max_length=100)),
                ('IN_DISCALCULIA', models.CharField(max_length=100)),
                ('IN_AUTISMO', models.CharField(max_length=100)),
                ('IN_IDOSO', models.CharField(max_length=100)),
                ('CO_MUNICIPIO_PROVA', models.CharField(max_length=100)),
                ('NO_MUNICIPIO_PROVA', models.CharField(max_length=100)),
                ('SG_UF_PROVA', models.CharField(max_length=100)),
                ('TP_PRESENCA_CN', models.CharField(max_length=100)),
                ('TP_PRESENCA_CH', models.CharField(max_length=100)),
                ('TP_PRESENCA_LC', models.CharField(max_length=100)),
                ('TP_PRESENCA_MT', models.CharField(max_length=100)),
                ('NU_NOTA_CN', models.FloatField()),
                ('NU_NOTA_CH', models.FloatField()),
                ('NU_NOTA_LC', models.FloatField()),
                ('NU_NOTA_MT', models.FloatField()),
                ('TP_LINGUA', models.CharField(max_length=100)),
                ('NU_NOTA_COMP1', models.FloatField()),
                ('NU_NOTA_COMP2', models.FloatField()),
                ('NU_NOTA_COMP3', models.FloatField()),
                ('NU_NOTA_COMP4', models.FloatField()),
                ('NU_NOTA_COMP5', models.FloatField()),
                ('NU_NOTA_REDACAO', models.CharField(max_length=100)),
                ('Q001', models.CharField(max_length=100)),
                ('Q002', models.CharField(max_length=100)),
                ('Q005', models.CharField(max_length=100)),
                ('Q006', models.CharField(max_length=100)),
                ('Q025', models.CharField(max_length=100)),
                ('Q026', models.CharField(max_length=100)),
            ],
        ),
    ]
